name: Publish docker image
run-name: ${{ github.actor }} is Publishing Package to npmjs with version ${{ github.ref_name }}
on:
  push:
    branches:
      - 8.2-fpm-nginx-alpine
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: 8.2/fpm-nginx-alpine/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/php:8.2-fpm-nginx-alpine
